spring:
  application:
    name: image-remove
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: image_user
    password: ${RABBITMQ_PASSWORD}

python:
  worker:
    url: http://10.0.0.248:5000

cloudflare:
  r2:
    bucket: background-remove
    access-key: ${R2_ACCESS_KEY}
    secret-key: ${R2_SECRET_KEY}
    endpoint: ${R2_ENDPOINT}
    public-url: ${R2_PUBLIC_URL}