spring:
  application:
    name: image-remove
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: image_user
    password: ${RABBITMQ_PASSWORD}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/image_db
    username: image_user
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

python:
  worker:
    url: http://10.0.0.248:5000

cloudflare:
  r2:
    bucket: background-remove
    access-key: ${R2_ACCESS_KEY}
    secret-key: ${R2_SECRET_KEY}
    endpoint: ${R2_ENDPOINT}
    public-url: ${R2_PUBLIC_URL}

jwt:
  issuer: image-remove
  secret-key: ${JWT_SECRET_KEY}

server:
  forward-headers-strategy: framework

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE